const express = require('express');
const router = express.Router();
const backupController = require('../controllers/backupController');
const authMiddleware = require('../middleware/auth');
const roleMiddleware = require('../middleware/role');
router.use(authMiddleware);
router.use(roleMiddleware(['admin']));
router.get('/', backupController.getAll);
router.post('/', backupController.create);
router.post('/restore/:filename', backupController.restore); 
router.get('/download/:filename', backupController.download);
router.delete('/:id', backupController.delete);
module.exports = router;