const express = require('express');
const router = express.Router();
const settingsController = require('../controllers/settingsController');
const authMiddleware = require('../middleware/auth');
const roleMiddleware = require('../middleware/role');
router.use(authMiddleware);
router.get('/public', settingsController.getPublic);
router.get('/', roleMiddleware(['admin']), settingsController.getAll);
router.put('/', roleMiddleware(['admin']), settingsController.update);
module.exports = router;